package com.sysgears.grain



final class GrainConstants {
    /**
     * Name prefix for scripts generated by template engine.
     */
    public static final String SCRIPT_NAME = "GrainScript"
    /**
     * Pattern for finding stack trace elements, related to html parsing issues.
     */
    public static final String GRAIN_SCRIPT_PATTERN = /^GrainScript\d+.*/
}
